image: node:16

options:
 max-time: 10
pipelines:
  branches:
    master:
      - step:
          name: Install Dependencies & Build Project
          size: 2x
          caches:
            - node
          script:
            - npm install --legacy-peer-deps
			- CI=false npm run build
          artifacts:
            - build/**
      - step:
          name: Deploy to master
          script:
            - scp -pvr build/* cbdev@143.110.176.134:/var/www/html/mine2mint